def remove_letters(input_string, letters_to_remove):
    return ''.join(char for char in input_string if char not in letters_to_remove)

alfabeto="abcdefghijklmnopqrstuvwxyz "
c=0
with open('a.txt', 'r') as file:
    line = file.readline()
    while line:
        x=line.replace('one', 'o1e')
        x=x.replace('two', 't2o')
        x=x.replace('three', 't3e')
        x=x.replace('four', 'f4r')
        x=x.replace('five', 'f5e')
        x=x.replace('six', 's6x')
        x=x.replace('seven', 's7n')
        x=x.replace('eight', 'e8t')
        x=x.replace('nine', 'n9e')
        x=x.replace('one', 'o1e')
        x=x.replace('two', 't2o')
        x=x.replace('three', 't3e')
        x=x.replace('four', 'f4r')
        x=x.replace('five', 'f5e')
        x=x.replace('six', 's6x')
        x=x.replace('seven', 's7n')
        x=x.replace('eight', 'e8t')
        x=x.replace('nine', 'n9e')
        x=x.replace('one', 'o1e')
        x=x.replace('two', 't2o')
        x=x.replace('three', 't3e')
        x=x.replace('four', 'f4r')
        x=x.replace('five', 'f5e')
        x=x.replace('six', 's6x')
        x=x.replace('seven', 's7n')
        x=x.replace('eight', 'e8t')
        x=x.replace('nine', 'n9e')
        x=x.replace('one', 'o1e')
        x=x.replace('two', 't2o')
        x=x.replace('three', 't3e')
        x=x.replace('four', 'f4r')
        x=x.replace('five', 'f5e')
        x=x.replace('six', 's6x')
        x=x.replace('seven', 's7n')
        x=x.replace('eight', 'e8t')
        x=x.replace('nine', 'n9e')
        x=x.replace('one', 'o1e')
        x=x.replace('two', 't2o')
        x=x.replace('three', 't3e')
        x=x.replace('four', 'f4r')
        x=x.replace('five', 'f5e')
        x=x.replace('six', 's6x')
        x=x.replace('seven', 's7n')
        x=x.replace('eight', 'e8t')
        x=x.replace('nine', 'n9e')
        x=x.replace('one', 'o1e')
        x=x.replace('two', 't2o')
        x=x.replace('three', 't3e')
        x=x.replace('four', 'f4r')
        x=x.replace('five', 'f5e')
        x=x.replace('six', 's6x')
        x=x.replace('seven', 's7n')
        x=x.replace('eight', 'e8t')
        x=x.replace('nine', 'n9e')
        x=x.replace('one', 'o1e')
        x=x.replace('two', 't2o')
        x=x.replace('three', 't3e')
        x=x.replace('four', 'f4r')
        x=x.replace('five', 'f5e')
        x=x.replace('six', 's6x')
        x=x.replace('seven', 's7n')
        x=x.replace('eight', 'e8t')
        x=x.replace('nine', 'n9e')
        x=x.replace('one', 'o1e')
        x=x.replace('two', 't2o')
        x=x.replace('three', 't3e')
        x=x.replace('four', 'f4r')
        x=x.replace('five', 'f5e')
        x=x.replace('six', 's6x')
        x=x.replace('seven', 's7n')
        x=x.replace('eight', 'e8t')
        x=x.replace('nine', 'n9e')
        x=x.replace('one', 'o1e')
        x=x.replace('two', 't2o')
        x=x.replace('three', 't3e')
        x=x.replace('four', 'f4r')
        x=x.replace('five', 'f5e')
        x=x.replace('six', 's6x')
        x=x.replace('seven', 's7n')
        x=x.replace('eight', 'e8t')
        x=x.replace('nine', 'n9e')
        x=x.replace('one', 'o1e')
        x=x.replace('two', 't2o')
        x=x.replace('three', 't3e')
        x=x.replace('four', 'f4r')
        x=x.replace('five', 'f5e')
        x=x.replace('six', 's6x')
        x=x.replace('seven', 's7n')
        x=x.replace('eight', 'e8t')
        x=x.replace('nine', 'n9e')
        linea=remove_letters(x,alfabeto)
        linea=linea.replace('\n', '')
        print(len(x))
        if len(linea)==1:
          #print(int(linea)*11)
          c=c+int(linea)*11
        else:
          #print(int(linea[0])*10+int(linea[len(linea)-1]))
          a=int(linea[0])*10
          b=int(linea[len(linea)-1])
          c=c+a+b
        line = file.readline()
print(c)
